<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-17T19:42:21 IST" name="Default suite" finished-at="2024-12-17T19:42:38 IST" duration-ms="17793">
    <groups>
    </groups>
    <test started-at="2024-12-17T19:42:21 IST" name="Default test" finished-at="2024-12-17T19:42:38 IST" duration-ms="17793">
      <class name="Part1.LoginShouldFailTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:Part1.LoginShouldFailTest@29215f06]" started-at="2024-12-17T19:42:21 IST" name="setup" finished-at="2024-12-17T19:42:29 IST" duration-ms="8210" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testLoggingIntoApplication()[pri:0, instance:Part1.LoginShouldFailTest@29215f06]" started-at="2024-12-17T19:42:29 IST" name="testLoggingIntoApplication" finished-at="2024-12-17T19:42:38 IST" duration-ms="8747" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Values should be different. Actual: Dashboard]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Values should be different. Actual: Dashboard
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failEquals(Assert.java:187)
at org.junit.Assert.assertNotEquals(Assert.java:163)
at org.junit.Assert.assertNotEquals(Assert.java:177)
at Part1.LoginShouldFailTest.testLoggingIntoApplication(LoginShouldFailTest.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoggingIntoApplication -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Part1.LoginShouldFailTest@29215f06]" started-at="2024-12-17T19:42:38 IST" name="tearDown" finished-at="2024-12-17T19:42:38 IST" duration-ms="785" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Part1.LoginShouldFailTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
